backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
  branch: master

media_folder: static/images
public_folder: /images

site_url: https://bambinakatarina.netlify.app/

collections:
  # Layout
  - name: layout
    label: Layout
    files:
      # Header
      - name: "header"
        label: "Header"
        file: "data/header.json"
        fields:
          - { name: title, label: Title, widget: string }
      # Social media links
      - name: "socialMedia"
        label: "Social Media"
        file: "data/social-media.json"
        fields:
          - name: socialMedia
            label: Social Media
            widget: list
            fields:
              - name: link
                label: Link
                widget: object
                fields:
                  - { name: name, label: Name, widget: string }
                  - { name: url, label: URL, widget: string }
  # Pages
  - name: pages
    label: Pages
    files:
      # Landing Page
      - name: "landing"
        label: "Landing Page"
        file: "data/landing.json"
        fields:
          - name: hero
            label: Hero
            widget: object
            collapsed: true
            fields:
              - name: image
                label: Image
                widget: object
                fields:
                  - { name: imagePath, label: Image, widget: image }
                  - {
                      name: alternateText,
                      label: Alternate text,
                      widget: string,
                    }
              - { name: pageTitle, label: Page Title, widget: string }
              - {
                  name: pageDescription,
                  label: Page Description,
                  widget: string,
                }

  # Blog Post Sections
  # TRAVEL
  - name: travel
    label: Travel Blog
    folder: data/blog/travel
    extension: json
    format: json
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: date,
          label: Date,
          dateFormat: "DD/MM/YYYY",
          timeFormat: HH:mm,
          widget: datetime,
        }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }

    # STYLE
  - name: style
    label: Style Blog
    folder: data/blog/style
    extension: json
    format: json
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: date,
          label: Date,
          dateFormat: "DD/MM/YYYY",
          timeFormat: HH:mm,
          widget: datetime,
        }
      - { name: body, label: Body, widget: markdown }

    # BOOKISH
  - name: bookish
    label: Bookish Blog
    folder: data/blog/bookish
    extension: json
    format: json
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: date,
          label: Date,
          dateFormat: "DD/MM/YYYY",
          timeFormat: HH:mm,
          widget: datetime,
        }
      - { name: body, label: Body, widget: markdown }
