backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

site_url: https://bambinakatarina.netlify.app/

collections:
  - name: travel
    label: Travel
    folder: blog/travel
    extension: json
    format: json
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: date,
          label: Date,
          dateFormat: "DD/MM/YYYY",
          timeFormat: HH:mm,
          widget: datetime,
        }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }

  - name: style
    label: Style
    folder: blog/style
    extension: json
    format: json
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: date,
          label: Date,
          dateFormat: "DD/MM/YYYY",
          timeFormat: HH:mm,
          widget: datetime,
        }
      - { name: body, label: Body, widget: markdown }

  - name: bookish
    label: Bookish
    folder: blog/bookish
    extension: json
    format: json
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: date,
          label: Date,
          dateFormat: "DD/MM/YYYY",
          timeFormat: HH:mm,
          widget: datetime,
        }
      - { name: body, label: Body, widget: markdown }
